import { ArticleDisplay } from '@/lib/types';

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 80);
}

export const sampleArticles: ArticleDisplay[] = [
  // AI DEVOPS
  {
    id: 'demo-devops-1',
    slug: slugify('The Rise of AI in DevOps CI CD Pipelines'),
    title: 'The Rise of AI in DevOps: Automating CI/CD Pipelines',
    summary: 'How artificial intelligence is transforming DevOps by predicting build failures, automating code reviews, and optimizing deployment strategies.',
    rewritten_content: 'AI is fundamentally changing how DevOps teams operate, moving from reactive to predictive systems.',
    full_rewritten_content: `## Predictive CI/CD: The New Standard\n\nAI-driven DevOps tools are now capable of analyzing historical build data to predict failures before they happen. By integrating machine learning models into CI/CD pipelines, teams can identify problematic code commits instantly.\n\n### Key Benefits of AIOps\n- **Automated Root Cause Analysis:** AI tools can scan logs across distributed microservices to pinpoint exactly why a deployment failed.\n- **Smart Resource Allocation:** Machine learning algorithms optimize cloud infrastructure dynamically based on load predictions.\n- **Enhanced Security Testing:** AI fuzzing and vulnerability scanning happen continuously without slowing down the pipeline.\n\nThe future of DevOps isn't just automation; it's autonomous operations where AI handles the routine scaling, testing, and deployment safely.`,
    original_url: 'https://example.com/ai-devops-future',
    source_name: 'DevOps Weekly',
    image_url: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&h=450&fit=crop',
    category: 'INDUSTRY',
    hypeScore: 8,
    realityCheck: 'While promising, fully autonomous pipelines still require human oversight for complex state changes.',
    tags: ['devops', 'ci-cd', 'automation'],
    published_date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-devops-2',
    slug: slugify('Terraform and AI Infrastructure as Code'),
    title: 'Generating Infrastructure as Code with LLMs',
    summary: 'Using Large Language Models to write, validate, and optimize Terraform and Kubernetes configurations.',
    rewritten_content: 'Developers are now using AI to draft complex infrastructure configurations in seconds.',
    full_rewritten_content: `## Infrastructure as Code, Accelerated\n\nWriting Terraform modules and Kubernetes manifests can be tedious and error-prone. New AI tools tailored for DevOps are changing this paradigm by allowing engineers to describe their infrastructure in plain English.\n\n### How it Works\nYou provide a prompt like: *"Create a highly available EKS cluster with 3 node groups, RDS PostgreSQL, and a Redis cache."*\nThe AI generates the complete Terraform configuration, ensuring best practices like IAM least privilege and proper tagging are applied out of the box.\n\n### Validation and Security\nMore impressively, AI is being used to lint and validate these configurations before deployment, catching security misconfigurations (like public S3 buckets) that traditional regex-based linters might miss.`,
    original_url: 'https://example.com/ai-iac',
    source_name: 'Cloud Native News',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop',
    category: 'AI_TUTORIALS',
    hypeScore: 9,
    realityCheck: 'Always review generated IaC. LLMs can occasionally suggest outdated API versions.',
    tags: ['terraform', 'kubernetes', 'cloud'],
    published_date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },

  // AI TOOLS FOR DAILY LIFE
  {
    id: 'demo-daily-1',
    slug: slugify('Top AI Tools for Daily Productivity'),
    title: '5 AI Tricks to Save 10 Hours a Week',
    summary: 'Practical, everyday AI tools and prompts that can automate your inbox, schedule, and daily writing tasks.',
    rewritten_content: 'You do not need to be a developer to benefit from AI. Here are practical ways to use it every day.',
    full_rewritten_content: `## Supercharge Your Daily Routine\n\nAI is no longer just a toy or a coding assistant; it's a powerful tool for personal productivity. Here are the top ways to integrate AI into your daily life:\n\n### 1. The Inbox Zero Assistant\nUse AI tools to auto-draft replies to routine emails. You can set up Zapier with GPT-4 to read incoming emails, categorize them, and draft potential responses for your review.\n\n### 2. Meeting Summaries\nNever take notes again. Tools like Otter.ai or Fireflies integrate into your calendar, record meetings, and provide concise summaries and action items.\n\n### 3. Meal Planning and Groceries\nPrompt an LLM with your dietary restrictions and what's in your fridge. It can generate a weekly meal plan and an exact grocery list formatted for your favorite delivery app.\n\n### 4. Personal Finance Parsing\nUpload bank statements (with PII removed) and ask AI to categorize expenses, find subscriptions you forgot about, and suggest budget optimizations.\n\nThese small daily integrations compound, saving you hours every week.`,
    original_url: 'https://example.com/ai-productivity',
    source_name: 'Lifehacker AI',
    image_url: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=450&fit=crop',
    category: 'AI_USE_CASES',
    hypeScore: 7,
    realityCheck: 'Setup takes a bit of time, but the recurring time savings are real.',
    tags: ['productivity', 'daily-life', 'hacks'],
    published_date: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-daily-2',
    slug: slugify('Perplexity AI Replacing Google Search'),
    title: 'How Perplexity AI is Replacing Traditional Web Search',
    summary: 'Why users are switching from Google to AI-powered answer engines for their daily queries and research.',
    rewritten_content: 'Answer engines are fundamentally changing how we look for information on the internet.',
    full_rewritten_content: `## The End of "10 Blue Links"\n\nFor decades, searching the web meant typing keywords and digging through pages of links (and ads) to find an answer. AI answer engines like Perplexity are shifting this paradigm.\n\n### Direct Answers with Citations\nInstead of giving you a list of websites, Perplexity reads the websites for you, synthesizes the information, and provides a direct, conversational answer with inline citations. This is incredibly useful for daily tasks:\n- *"What are the entry requirements for traveling to Japan right now?"*\n- *"Compare the latest features of iOS 18 vs Android 15."*\n\n### Why it Wins for Daily Life\nIt saves the cognitive load of evaluating multiple sources. While hallucination was a major concern early on, the strict grounding in real-time web results has made these tools highly reliable for everyday research.`,
    original_url: 'https://example.com/perplexity-search',
    source_name: 'Tech Trends',
    image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=450&fit=crop',
    category: 'AI_TOOLS',
    hypeScore: 8,
    realityCheck: 'Excellent for direct answers, but traditional search is still better for navigating to specific domains.',
    tags: ['search', 'perplexity', 'tools'],
    published_date: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },

  // AI MODELS AND FEATURES
  {
    id: 'demo-models-1',
    slug: slugify('Understanding the Different Types of AI Models'),
    title: 'Decoding AI Models: LLMs, Diffusion, and Multimodal',
    summary: 'A comprehensive guide to the different types of AI models available today and what each is best used for.',
    rewritten_content: 'Not all AI models are the same. Understanding their architectures helps you choose the right tool for the job.',
    full_rewritten_content: `## The AI Model Zoo\n\nWith new models launching weekly, it's easy to get confused. Here is a breakdown of the main types of AI models and their features:\n\n### 1. Large Language Models (LLMs)\n**Examples:** GPT-4, Claude 3, Llama 3\n**Best For:** Text generation, reasoning, coding, summarization. They are the "brains" of chatbots.\n\n### 2. Diffusion Models\n**Examples:** Midjourney, Stable Diffusion, DALL-E 3\n**Best For:** Image generation. They work by adding random noise to data and then learning to reverse the process to construct an image from a text prompt.\n\n### 3. Multimodal Models\n**Examples:** Gemini 1.5 Pro, GPT-4o\n**Best For:** Processing multiple types of input natively. They don't just "read" text; they can "see" images and video, and "hear" audio directly without needing separate translation models.\n\n### 4. Small Language Models (SLMs)\n**Examples:** Phi-3, Gemma\n**Best For:** Running locally on phones or laptops. They are highly optimized and trained on heavily curated data to provide high performance with low resource requirements.`,
    original_url: 'https://example.com/ai-model-types',
    source_name: 'AI Research Weekly',
    image_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=450&fit=crop',
    category: 'RESEARCH',
    hypeScore: 6,
    realityCheck: 'The lines between these categories are blurring as models become increasingly multimodal.',
    tags: ['llm', 'models', 'education'],
    published_date: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-models-2',
    slug: slugify('Claude 3.5 vs GPT-4o Which Model Should You Use'),
    title: 'Claude 3.5 Sonnet vs GPT-4o: Feature Comparison',
    summary: 'A deep dive into the features, strengths, and weaknesses of the current top-tier AI models.',
    rewritten_content: 'Choosing between the heavyweights: Anthropic\\'s Claude 3.5 Sonnet and OpenAI\\'s GPT-4o.',
    full_rewritten_content: `## The Battle of the Titans\n\nThe competition between OpenAI and Anthropic is driving rapid innovation. Here is how their flagship models compare in features:\n\n### Claude 3.5 Sonnet\n**Key Features:**\n- **Artifacts:** A dedicated UI panel that renders code, SVGs, and documents natively alongside the chat.\n- **Speed:** Blazing fast generation, making it ideal for real-time coding.\n- **Nuance:** Generally considered superior at creative writing and adhering strictly to complex formatting constraints without "lazy" outputs.\n\n### GPT-4o\n**Key Features:**\n- **Native Voice & Vision:** Incredible real-time audio conversation capabilities with emotion detection and extremely fast vision processing.\n- **Ecosystem:** Deeply integrated with data analysis tools, web browsing, and custom GPTs.\n- **Multilingual:** Superior performance across non-English languages.\n\n### The Verdict\nFor developers and writers, Claude 3.5 Sonnet's Artifacts feature and coding ability make it the current favorite. For general consumers and real-time voice interactions, GPT-4o remains unmatched.`,
    original_url: 'https://example.com/claude-vs-gpt4o',
    source_name: 'Model Benchmarks',
    image_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop',
    category: 'PRODUCT_LAUNCH',
    hypeScore: 9,
    realityCheck: 'Both models are phenomenal; the choice largely depends on whether you prefer Anthropic\\'s UI (Artifacts) or OpenAI\\'s ecosystem.',
    tags: ['claude', 'gpt4', 'comparison'],
    published_date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  }
];
